//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DesarrolloDataEntities : DbContext
    {
        public DesarrolloDataEntities()
            : base("name=DesarrolloDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Operacion> Operacions { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    
        public virtual int OperacionAdd(string numero, Nullable<int> resultado, Nullable<int> idUsuario)
        {
            var numeroParameter = numero != null ?
                new ObjectParameter("Numero", numero) :
                new ObjectParameter("Numero", typeof(string));
    
            var resultadoParameter = resultado.HasValue ?
                new ObjectParameter("Resultado", resultado) :
                new ObjectParameter("Resultado", typeof(int));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OperacionAdd", numeroParameter, resultadoParameter, idUsuarioParameter);
        }
    
        public virtual int OperacionDelete(Nullable<int> idOperacion)
        {
            var idOperacionParameter = idOperacion.HasValue ?
                new ObjectParameter("idOperacion", idOperacion) :
                new ObjectParameter("idOperacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OperacionDelete", idOperacionParameter);
        }
    
        public virtual int OperacionFechaUpdate(Nullable<int> idOperacion)
        {
            var idOperacionParameter = idOperacion.HasValue ?
                new ObjectParameter("idOperacion", idOperacion) :
                new ObjectParameter("idOperacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OperacionFechaUpdate", idOperacionParameter);
        }
    
        public virtual ObjectResult<OperacionGetAll_Result> OperacionGetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OperacionGetAll_Result>("OperacionGetAll");
        }
    
        public virtual ObjectResult<OperacionGetById_Result> OperacionGetById(Nullable<int> idOperacion)
        {
            var idOperacionParameter = idOperacion.HasValue ?
                new ObjectParameter("idOperacion", idOperacion) :
                new ObjectParameter("idOperacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OperacionGetById_Result>("OperacionGetById", idOperacionParameter);
        }
    
        public virtual ObjectResult<OperacionGetByUser_Result> OperacionGetByUser(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OperacionGetByUser_Result>("OperacionGetByUser", idUsuarioParameter);
        }
    
        public virtual int UsuarioAdd(string userName, string contraseña)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            var contraseñaParameter = contraseña != null ?
                new ObjectParameter("contraseña", contraseña) :
                new ObjectParameter("contraseña", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UsuarioAdd", userNameParameter, contraseñaParameter);
        }
    
        public virtual int UsuarioDelete(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UsuarioDelete", idUsuarioParameter);
        }
    
        public virtual ObjectResult<UsuarioGetAll_Result> UsuarioGetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UsuarioGetAll_Result>("UsuarioGetAll");
        }
    
        public virtual ObjectResult<UsuarioGetById_Result> UsuarioGetById(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UsuarioGetById_Result>("UsuarioGetById", idUsuarioParameter);
        }
    
        public virtual int OperacionDeleteAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OperacionDeleteAll");
        }
    }
}
